print('     /~\\')
print('    ( oo|')
print('    _\=/_')
print('   /  _  \\')
print('  //|/.\|\\\\')  # 여기 마지막에 \총4개임 ㅇㅇ. 2개표현하기 위해 \2개 추가
print(' ||  \ /  ||')
print('============')
print('|          |')
print('|          |')
print('|          |')
